# Setup
title: Feinkost Internet
description: >-
  Gegründet 2017 im Süden von Deutschland wurde der Traditionsbetrieb über Nacht
  der Geheimtipp für frisches Internet. Bei Feinkost Internet steht seit jeher
  die Liebe zum Internet im Vordergrund der Traditionsmanufaktur. Noch heute
  kommen die Gründer zusammen, sprechen ihren Podcast von Hand ein und tragen
  persönlich Sorge dafür, dass aus aktueller Technologie, deinem Spamfolder und
  dem neuen Film von Til Schweiger saftiges Internet wird.
baseurl: ""
statisticsUrl: "http://media.blubrry.com/feinkost_internet/"
url: "http://www.feinkost-internet.de"

paginate: 10
paginate_path: "/:num"

# About/contact
author:
  name: Feinkost Internet
  email: feinkost.internet@gmail.com
  url:  http://feinkost-internet.de

# Gems
plugins:
  - jekyll-paginate
  - jekyll-seo-tag

sass:
  style: compressed
  sass_dir: _styles

lang: de_DE

#Others
markdown: kramdown
excerpt_separator: <!--more-->
include: ["_pages"]

header_links:
  - name: Episoden
    url: /
  - name: Über uns
    url: /ueber-uns.html
  - name: Archiv
    url: /archiv.html
  - name: Impressum
    url: /impressum.html

# Podcast
podcast_feed_url: "http://feinkost-internet.de/feed/podcast.xml"
podcast_language: de-DE
podcast_album_art: /assets/img/logo-3000x3000.jpg
podcast_title: Feinkost Internet

podcast_categories:
  - name: Comedy
  - name: Technology
    sub_categories:
      - name: Tech News
podcast_explicit: "no"
podcast_subtitle: "Letzte Feinkost vor dem Internet"

# Social Media
twitter:
  username: "internetkost"

defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/logo.jpg

# SEO
logo: "/assets/img/logo.jpg"
# webmaster_verifications:
#   google: 1234
