# Setup
title:        Feinkost Internet
tagline:      Just Another Podcast
baseurl:      ""
# paginate:     1

# About/contact
author:
  name: Feinkost Internet
  url:  https://feinhost-internet.de

# Gems
plugins:
  - jekyll-paginate

sass:
  style: compressed
  sass_dir: _styles

#Others
markdown: kramdown
excerpt_separator: <!--more-->

# Podcast
feed_url: https://feinkost-internet.github.io/feed.rss