# Setup
title:        Feinkost Internet
tagline:      Just Another Podcast
description:  ""
baseurl:      ""
url:          "http://feinhost-internet.de"
# paginate:     1

# About/contact
author:
  name: Feinkost Internet
  url:  http://feinhost-internet.de

# Gems
plugins:
  - jekyll-paginate
  - jekyll-seo-tag

sass:
  style: compressed
  sass_dir: _styles

#Others
markdown: kramdown
excerpt_separator: <!--more-->
include: ["_pages"]

header_links:
  - name: Episoden
    url: /
  - name: Über uns
    url: /ueber-uns.html
  - name: Impressum
    url: /impressum.html

# Podcast
podcast_feed: /feed/podcast.xml
podcast_language: de-DE
podcast_album_art: /assets/podcast/cover-v0.jpg
podcast_title: Feinkost Internet
podcast_owner: Feinkost Internet
podcast_email: feinkost.internet@gmail.com
podcast_category: Technology
podcast_subcategory_one: Tech News
podcast_subcategory_two: Gadgets
podcast_explicit: "no"
podcast_author: Feinkost Internet
podcast_description: "Lorem Ipsum"
podcast_summary: "Lorem Ipsum"
podcast_subtitle: "Lorem Ipsum"

# Social Media
twitter:
  username: ""

# SEO
logo: "assets/img/logo.jpg"
webmaster_verifications:
  google: 1234
