# Setup
title:        Feinkost Internet
tagline:      Just Another Podcast
description: |
  Gegründet 2017 im Süden von Deutschland wurde der Traditionsbetrieb über Nacht
  der Geheimtipp für frisches Internet. Bei Feinkost Internet steht seit jeher
  die Liebe zum Internet im Vordergrund der Traditionsmanufaktur. Noch heute
  kommen die Gründer zusammen, sprechen ihren Podcast von Hand ein und tragen
  persönlich Sorge dafür das aus aktueller Technologie, deinem Spamfolder und
  dem neuen Film von Til Schweiger saftiges Internet wird.
baseurl:      ""
url:          "http://www.feinkost-internet.de"
# paginate:     1

# About/contact
author:
  name: Feinkost Internet
  url:  http://www.feinkost-internet.de

# Gems
plugins:
  - jekyll-paginate
  - jekyll-seo-tag

sass:
  style: compressed
  sass_dir: _styles

#Others
markdown: kramdown
excerpt_separator: <!--more-->
include: ["_pages"]

header_links:
  - name: Episoden
    url: /
  - name: Über uns
    url: /ueber-uns.html
  - name: Impressum
    url: /impressum.html

# Podcast
podcast_feed: /feed/podcast.xml
podcast_language: de-DE
podcast_album_art: /assets/img/logo-3000x3000.jpg
podcast_title: Feinkost Internet
podcast_owner: Feinkost Internet
podcast_email: feinkost.internet@gmail.com

podcast_categories:
  - name: Comedy
  - name: Technology
    sub_categories:
      - name: Tech News
podcast_explicit: "no"
podcast_author: Feinkost Internet
podcast_subtitle: "Letzte Feinkost vor dem Internet"

# Social Media
twitter:
  username: ""

defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/logo.jpg

# SEO
logo: "/assets/img/logo.jpg"
webmaster_verifications:
  google: 1234
