# Setup
title:        Feinkost Internet
tagline:      Just Another Podcast
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Josa Gesell
  url:        http://yourhomepage.com 

# Gems
plugins:
  - jekyll-paginate

#Others
markdown: kramdown