# Setup
title:        Feinkost Internet
tagline:      Just Another Podcast
baseurl:      ""
# paginate:     1

# About/contact
author:
  name: Feinkost Internet
  url:  https://feinhost-internet.de

# Gems
plugins:
  - jekyll-paginate

#Others
markdown: kramdown
excerpt_separator: <!--more-->