name: 'Schedule'
on:
  schedule:
    - cron: '*/15 * * * *'
jobs:
  publish:
    name:    'Publish master'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@master'
      - uses: 'josa42/gh-action-webhook/latest@master'
        with:
          url:           'https://api.github.com/repos/feinkost-internet/feinkost-internet.github.io/pages/builds'
          authorization: 'Token ${{ secrets.GITHUB_BUILD_TOKEN }}'
          accept:        'application/vnd.github.mister-fantastic-preview+json'
